//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListenedList {
    
    
    public partial class _Default {
        
        /// <summary>
        /// yearBox83 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ListenedList.Controls.YearBoxes yearBox83;
        
        /// <summary>
        /// yearBox1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ListenedList.Controls.YearBoxes yearBox1;
        
        /// <summary>
        /// yearBox2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ListenedList.Controls.YearBoxes yearBox2;
        
        /// <summary>
        /// yearBox3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ListenedList.Controls.YearBoxes yearBox3;
        
        /// <summary>
        /// yearBox4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ListenedList.Controls.YearBoxes yearBox4;
        
        /// <summary>
        /// yearBox5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ListenedList.Controls.YearBoxes yearBox5;
        
        /// <summary>
        /// yearBox6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ListenedList.Controls.YearBoxes yearBox6;
        
        /// <summary>
        /// yearBox7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ListenedList.Controls.YearBoxes yearBox7;
        
        /// <summary>
        /// yearBox8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ListenedList.Controls.YearBoxes yearBox8;
        
        /// <summary>
        /// yearBox9 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ListenedList.Controls.YearBoxes yearBox9;
        
        /// <summary>
        /// yearBox10 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ListenedList.Controls.YearBoxes yearBox10;
        
        /// <summary>
        /// yearBox11 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ListenedList.Controls.YearBoxes yearBox11;
        
        /// <summary>
        /// yearBox12 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ListenedList.Controls.YearBoxes yearBox12;
        
        /// <summary>
        /// yearBox13 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ListenedList.Controls.YearBoxes yearBox13;
        
        /// <summary>
        /// yearBox14 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ListenedList.Controls.YearBoxes yearBox14;
        
        /// <summary>
        /// yearBox15 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ListenedList.Controls.YearBoxes yearBox15;
        
        /// <summary>
        /// yearBox16 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ListenedList.Controls.YearBoxes yearBox16;
        
        /// <summary>
        /// yearBox17 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ListenedList.Controls.YearBoxes yearBox17;
        
        /// <summary>
        /// yearBox18 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ListenedList.Controls.YearBoxes yearBox18;
        
        /// <summary>
        /// yearBox19 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ListenedList.Controls.YearBoxes yearBox19;
        
        /// <summary>
        /// yearBox20 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ListenedList.Controls.YearBoxes yearBox20;
        
        /// <summary>
        /// yearBox21 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ListenedList.Controls.YearBoxes yearBox21;
        
        /// <summary>
        /// yearBox22 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ListenedList.Controls.YearBoxes yearBox22;
        
        /// <summary>
        /// yearBox23 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ListenedList.Controls.YearBoxes yearBox23;
        
        /// <summary>
        /// hdnUserId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hdnUserId;
    }
}
